export enum HttpError {
    SERVER_ERROR       = "SERVER_ERROR",
    RESOURCE_DUPLICATE = "RESOURCE_DUPLICATE",
    RESOURCE_NOT_EXIST = "RESOURCE_NOT_EXIST",
    USER_NOT_EXIST     = "USER_NOT_EXIST",
    PASSWORD_INCORRECT = "PASSWORD_INCORRECT",
  }